import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import Navbar from "@/components/navbar";
import AuthProvider from "@/components/providers/AuthProvider";

const poppins = Poppins({
  subsets:['latin'],
  weight:'400'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${poppins.className} antialiased flex`}
      >
        <AuthProvider>
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full">
            <SidebarTrigger />
            <Navbar />
            {children}
          </main>
        </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
